- type: dnf
    repos:
      cleanup: true
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      copr:
        - secureblue/packages
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      packages:
        - brave-browser
        - bubblejail
        - kdiskmark
        - clamav
        - clamav-update
        - rkhunter
        - lynis
        - papirus-icon-theme
        - python3-pip
        - fcitx5
        - fcitx5-hangul
        - fcitx5-configtool
        - fcitx5-qt
        - fcitx5-gtk
        - google-noto-fonts-common
        - google-noto-sans-fonts
        - google-noto-serif-fonts
        - google-noto-mono-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-serif-cjk-fonts
        - google-noto-emoji-fonts
    remove:
      packages:
        - firefox
        - firefox-langpacks
